name: ganf_app
description: Ganf, Automating Anywhere

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.1.1
  dio: ^3.0.9
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0

  cupertino_icons: ^1.0.0
  carousel_slider: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - ganf-logo.png
